import type { NextPage } from "next";
import Head from "next/head";
import styles from "@src/styles/404.module.scss";

const Custom404: NextPage = () => {
  return (
    <div className={styles.Page404}>
      <Head>
        <title>LoaCalc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div>
          <h1 className={styles.Page404__Status}>404</h1>
          <div className={styles.Page404__ContentDivider}>
            <h2 className={styles.Page404__ContentText}>
              This page could not be found
            </h2>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Custom404;
