import type { NextPage, GetStaticPropsContext } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";
import styles from "@src/styles/Home.module.css";

const Menu3: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>LoaCalc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>menu3</div>
      </main>
    </div>
  );
};

export async function getStaticProps(context: GetStaticPropsContext) {
  const { locale } = context;

  return {
    props: {
      ...(await serverSideTranslations(locale as string, [
        "common",
        "footer",
        "header",
      ])),
    }, // will be passed to the page component as props
  };
}

export default Menu3;
