version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/loa-calc/ # 프로젝트 이름
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 320
      runas: ubuntu
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 320
      runas: ubuntu
  ValidateService:
    - location: scripts/ValidateService.sh
      timeout: 30
      runas: ubuntu
